# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dashboard.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PIDpy(object):
    def setupUi(self, PIDpy):
        PIDpy.setObjectName("PIDpy")
        PIDpy.resize(1020, 883)
        PIDpy.setInputMethodHints(QtCore.Qt.ImhNone)
        self.centralwidget = QtWidgets.QWidget(PIDpy)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(90, 60, 301, 81))
        font = QtGui.QFont()
        font.setPointSize(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.startButton = QtWidgets.QPushButton(self.centralwidget)
        self.startButton.setGeometry(QtCore.QRect(860, 80, 113, 32))
        self.startButton.setObjectName("startButton")
        self.kpLabel = QtWidgets.QLabel(self.centralwidget)
        self.kpLabel.setGeometry(QtCore.QRect(560, 50, 21, 16))
        self.kpLabel.setObjectName("kpLabel")
        self.kiLabel = QtWidgets.QLabel(self.centralwidget)
        self.kiLabel.setGeometry(QtCore.QRect(560, 90, 16, 16))
        self.kiLabel.setObjectName("kiLabel")
        self.kdLabel = QtWidgets.QLabel(self.centralwidget)
        self.kdLabel.setGeometry(QtCore.QRect(560, 130, 21, 16))
        self.kdLabel.setObjectName("kdLabel")
        self.setPointLabel = QtWidgets.QLabel(self.centralwidget)
        self.setPointLabel.setGeometry(QtCore.QRect(700, 90, 60, 16))
        self.setPointLabel.setObjectName("setPointLabel")
        self.kp = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.kp.setGeometry(QtCore.QRect(590, 43, 68, 31))
        self.kp.setMinimum(-99.99)
        self.kp.setObjectName("kp")
        self.kp_2 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.kp_2.setGeometry(QtCore.QRect(590, 80, 68, 31))
        self.kp_2.setMinimum(-99.99)
        self.kp_2.setObjectName("kp_2")
        self.kp_3 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.kp_3.setGeometry(QtCore.QRect(590, 120, 68, 31))
        self.kp_3.setMinimum(-99.99)
        self.kp_3.setObjectName("kp_3")
        self.kp_4 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.kp_4.setGeometry(QtCore.QRect(760, 80, 81, 31))
        self.kp_4.setMinimum(-99.99)
        self.kp_4.setObjectName("kp_4")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(30, 220, 961, 601))
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.outputPlot = QtWidgets.QWidget(self.widget)
        self.outputPlot.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.outputPlot.setObjectName("outputPlot")
        self.gridLayout_2.addWidget(self.outputPlot, 0, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.kpPlot = QtWidgets.QWidget(self.widget)
        self.kpPlot.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.kpPlot.setObjectName("kpPlot")
        self.gridLayout.addWidget(self.kpPlot, 0, 0, 1, 1)
        self.kiPlot = QtWidgets.QWidget(self.widget)
        self.kiPlot.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.kiPlot.setObjectName("kiPlot")
        self.gridLayout.addWidget(self.kiPlot, 1, 0, 1, 1)
        self.kdPlot = QtWidgets.QWidget(self.widget)
        self.kdPlot.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.kdPlot.setObjectName("kdPlot")
        self.gridLayout.addWidget(self.kdPlot, 2, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 1, 2, 1)
        self.errorPlot = QtWidgets.QWidget(self.widget)
        self.errorPlot.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.errorPlot.setObjectName("errorPlot")
        self.gridLayout_2.addWidget(self.errorPlot, 1, 0, 1, 1)
        PIDpy.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(PIDpy)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1020, 24))
        self.menubar.setObjectName("menubar")
        PIDpy.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(PIDpy)
        self.statusbar.setObjectName("statusbar")
        PIDpy.setStatusBar(self.statusbar)

        self.retranslateUi(PIDpy)
        QtCore.QMetaObject.connectSlotsByName(PIDpy)

    def retranslateUi(self, PIDpy):
        _translate = QtCore.QCoreApplication.translate
        PIDpy.setWindowTitle(_translate("PIDpy", "PIDpy"))
        self.label.setText(_translate("PIDpy", "PID Visualizer"))
        self.startButton.setText(_translate("PIDpy", "Start"))
        self.kpLabel.setText(_translate("PIDpy", "Kp"))
        self.kiLabel.setText(_translate("PIDpy", "Ki"))
        self.kdLabel.setText(_translate("PIDpy", "Kd"))
        self.setPointLabel.setText(_translate("PIDpy", "Set point"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PIDpy = QtWidgets.QMainWindow()
    ui = Ui_PIDpy()
    ui.setupUi(PIDpy)
    PIDpy.show()
    sys.exit(app.exec_())
