# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dashboard.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PIDpy(object):
    def setupUi(self, PIDpy):
        PIDpy.setObjectName("PIDpy")
        PIDpy.resize(1020, 883)
        self.centralwidget = QtWidgets.QWidget(PIDpy)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(90, 60, 301, 81))
        font = QtGui.QFont()
        font.setPointSize(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(860, 80, 113, 32))
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(560, 50, 21, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(560, 90, 16, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(560, 130, 21, 16))
        self.label_4.setObjectName("label_4")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(590, 40, 91, 31))
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(590, 80, 91, 31))
        self.textEdit_2.setObjectName("textEdit_2")
        self.textEdit_3 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_3.setGeometry(QtCore.QRect(590, 120, 91, 31))
        self.textEdit_3.setObjectName("textEdit_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(760, 50, 60, 16))
        self.label_5.setObjectName("label_5")
        self.textEdit_4 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_4.setGeometry(QtCore.QRect(740, 80, 91, 31))
        self.textEdit_4.setObjectName("textEdit_4")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(30, 220, 961, 601))
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widget1 = QtWidgets.QWidget(self.widget)
        self.widget1.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.widget1.setObjectName("widget1")
        self.gridLayout_2.addWidget(self.widget1, 0, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.widget_3 = QtWidgets.QWidget(self.widget)
        self.widget_3.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.widget_3.setObjectName("widget_3")
        self.gridLayout.addWidget(self.widget_3, 0, 0, 1, 1)
        self.widget_4 = QtWidgets.QWidget(self.widget)
        self.widget_4.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.widget_4.setObjectName("widget_4")
        self.gridLayout.addWidget(self.widget_4, 1, 0, 1, 1)
        self.widget_5 = QtWidgets.QWidget(self.widget)
        self.widget_5.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.widget_5.setObjectName("widget_5")
        self.gridLayout.addWidget(self.widget_5, 2, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 1, 2, 1)
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_2.addWidget(self.widget_2, 1, 0, 1, 1)
        PIDpy.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(PIDpy)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1020, 24))
        self.menubar.setObjectName("menubar")
        PIDpy.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(PIDpy)
        self.statusbar.setObjectName("statusbar")
        PIDpy.setStatusBar(self.statusbar)

        self.retranslateUi(PIDpy)
        QtCore.QMetaObject.connectSlotsByName(PIDpy)

    def retranslateUi(self, PIDpy):
        _translate = QtCore.QCoreApplication.translate
        PIDpy.setWindowTitle(_translate("PIDpy", "PIDpy"))
        self.label.setText(_translate("PIDpy", "PID Visualizer"))
        self.pushButton.setText(_translate("PIDpy", "Start"))
        self.label_2.setText(_translate("PIDpy", "Kp"))
        self.label_3.setText(_translate("PIDpy", "Ki"))
        self.label_4.setText(_translate("PIDpy", "Kd"))
        self.label_5.setText(_translate("PIDpy", "Set point"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PIDpy = QtWidgets.QMainWindow()
    ui = Ui_PIDpy()
    ui.setupUi(PIDpy)
    PIDpy.show()
    sys.exit(app.exec_())
