# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dashboard.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PIDpy(object):
    def setupUi(self, PIDpy):
        PIDpy.setObjectName("PIDpy")
        PIDpy.resize(1020, 883)
        PIDpy.setInputMethodHints(QtCore.Qt.ImhNone)
        self.centralwidget = QtWidgets.QWidget(PIDpy)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(90, 60, 301, 81))
        font = QtGui.QFont()
        font.setPointSize(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.startButton = QtWidgets.QPushButton(self.centralwidget)
        self.startButton.setGeometry(QtCore.QRect(860, 80, 113, 32))
        self.startButton.setObjectName("startButton")
        self.kpLabel = QtWidgets.QLabel(self.centralwidget)
        self.kpLabel.setGeometry(QtCore.QRect(560, 50, 21, 16))
        self.kpLabel.setObjectName("kpLabel")
        self.kiLabel = QtWidgets.QLabel(self.centralwidget)
        self.kiLabel.setGeometry(QtCore.QRect(560, 90, 16, 16))
        self.kiLabel.setObjectName("kiLabel")
        self.kdLabel = QtWidgets.QLabel(self.centralwidget)
        self.kdLabel.setGeometry(QtCore.QRect(560, 130, 21, 16))
        self.kdLabel.setObjectName("kdLabel")
        self.setPointLabel = QtWidgets.QLabel(self.centralwidget)
        self.setPointLabel.setGeometry(QtCore.QRect(700, 90, 60, 16))
        self.setPointLabel.setObjectName("setPointLabel")
        self.kp = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.kp.setGeometry(QtCore.QRect(590, 43, 68, 31))
        self.kp.setMinimum(-99.99)
        self.kp.setObjectName("kp")
        self.ki = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.ki.setGeometry(QtCore.QRect(590, 80, 68, 31))
        self.ki.setMinimum(-99.99)
        self.ki.setObjectName("ki")
        self.kd = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.kd.setGeometry(QtCore.QRect(590, 120, 68, 31))
        self.kd.setMinimum(-99.99)
        self.kd.setObjectName("kd")
        self.setpoint = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.setpoint.setGeometry(QtCore.QRect(760, 80, 81, 31))
        self.setpoint.setMinimum(-99.99)
        self.setpoint.setObjectName("setpoint")
        self.OutputGraph = PlotWidget(self.centralwidget)
        self.OutputGraph.setGeometry(QtCore.QRect(40, 180, 461, 291))
        self.OutputGraph.setAutoFillBackground(True)
        self.OutputGraph.setObjectName("OutputGraph")
        self.ErrorGraph = PlotWidget(self.centralwidget)
        self.ErrorGraph.setGeometry(QtCore.QRect(40, 490, 461, 291))
        self.ErrorGraph.setAutoFillBackground(True)
        self.ErrorGraph.setObjectName("ErrorGraph")
        self.KiGraph = PlotWidget(self.centralwidget)
        self.KiGraph.setGeometry(QtCore.QRect(520, 390, 461, 181))
        self.KiGraph.setAutoFillBackground(True)
        self.KiGraph.setObjectName("KiGraph")
        self.KdGraph = PlotWidget(self.centralwidget)
        self.KdGraph.setGeometry(QtCore.QRect(520, 600, 461, 181))
        self.KdGraph.setAutoFillBackground(True)
        self.KdGraph.setObjectName("KdGraph")
        self.KpGraph = PlotWidget(self.centralwidget)
        self.KpGraph.setGeometry(QtCore.QRect(520, 180, 461, 181))
        self.KpGraph.setAutoFillBackground(True)
        self.KpGraph.setObjectName("KpGraph")
        PIDpy.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(PIDpy)
        self.statusbar.setObjectName("statusbar")
        PIDpy.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(PIDpy)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1020, 24))
        self.menubar.setObjectName("menubar")
        PIDpy.setMenuBar(self.menubar)

        self.retranslateUi(PIDpy)
        QtCore.QMetaObject.connectSlotsByName(PIDpy)

    def retranslateUi(self, PIDpy):
        _translate = QtCore.QCoreApplication.translate
        PIDpy.setWindowTitle(_translate("PIDpy", "PIDpy"))
        self.label.setText(_translate("PIDpy", "PID Visualizer"))
        self.startButton.setText(_translate("PIDpy", "Start"))
        self.kpLabel.setText(_translate("PIDpy", "Kp"))
        self.kiLabel.setText(_translate("PIDpy", "Ki"))
        self.kdLabel.setText(_translate("PIDpy", "Kd"))
        self.setPointLabel.setText(_translate("PIDpy", "Set point"))
from pyqtgraph import PlotWidget
